<?php

?>
<!DOCTYPE html>
<html>
<head>
  <title>record</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i%7CQuicksand:300,400,500,700" rel="stylesheet">

    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="../assets/admin/vendors/css/vendors.min.css">
    <link rel="stylesheet" type="text/css" href="../assets/admin/vendors/css/forms/icheck/icheck.css">
    <link rel="stylesheet" type="text/css" href="../assets/admin/vendors/css/line/css/line-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="../assets/admin/vendors/css/line/css/line-awesome.css">
    
    <link rel="stylesheet" type="text/css" href="../assets/admin/vendors/css/forms/icheck/custom.css">
    <link rel="stylesheet" type="text/css" href="../assets/admin/vendors/css/ui/jquery-ui.min.css">
    <link rel="stylesheet" type="text/css" href="../assets/admin/vendors/css/forms/selects/select2.min.css">
    <!-- END: Vendor CSS-->

    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="../assets/admin/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="../assets/admin/css/bootstrap-extended.css">
    <link rel="stylesheet" type="text/css" href="../assets/admin/css/colors.css">
    <link rel="stylesheet" type="text/css" href="../assets/admin/css/components.css">
    <!-- END: Theme CSS-->

    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="../assets/admin/css/core/menu/menu-types/horizontal-menu.css">
    <link rel="stylesheet" type="text/css" href="../assets/admin/css/core/colors/palette-gradient.css">
    <!-- END: Page CSS-->

    <!-- END: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="../assets/admin/vendors/css/tables/datatable/datatables.min.css">
    <link rel="stylesheet" type="text/css" href="../assets/admin/css/plugins/forms/validation/form-validation.css">
    <link rel="stylesheet" type="text/css" href="../assets/admin/vendors/css/extensions/sweetalert.css">
</head>

<style type="text/css">
		body {
		margin: 20px;
		padding: 20px;
		font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif; 
	   	font-weight: 300;
	}
	table {  
    border-collapse: collapse; 
    border-spacing: 0;
}
td, th { border: 1px solid #CCC; } 
.fon{
	font-size:1vw;
}
@media print{
  body * {
    visibility: hidden;
  }
  .print-part, .print-part * {
    visibility: visible;
  }
}
</style>
<body>
<?php
require_once('../assets/constants/config.php');
if (isset($_POST['save'])) {
$today=date('y-m-d');
$repid = $_POST["repid"];
$title = $_POST["title"];
$PreparedBy = $_POST["PreparedBy"];
$contact = $_POST["telephone"];
$email = $_POST["email"];
$cont = $_POST["content"];
$branch=$_POST['branch'];

$sqlRep="INSERT INTO `report`(`report_id`, `Title`, `prepare_by`, `contact`, `email`, `sent_date`, `content`, `document`) VALUES ('$repid','$title','$PreparedBy','$contact','$email','$today','$cont','')";
$resultRep=mysqli_query($con,$sqlRep);
       if ($resultRep===true) {
   
     } else {
      
      echo "check your enserted item id, that must be unique";
    }


?>

<div class="print-part">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body p-0">
                  

                    <div class="row pb-5 p-5">
                        <div class="col-md-6">
                            <p class="font-weight-bold mb-4">Report <?php echo $repid; ?>: <?php echo $title; ?></p>
                            <p class="mb-1">Generated By: <?php echo $PreparedBy; ?></p>
                            <p> Phone Number: <?php echo $contact; ?></p>
                            <p class="mb-1">Email address: <?php echo $email; ?></p>
                            <p class="mb-1">Content :<?php echo $cont; ?></p>
                            <p class="mb-1">Branch :<?php echo $branch; ?></p>
                        </div>

                    </div>
    <div class="">
<div class=" table-responsive">
  <table id="ManageItem" class="table table-bordered">
    <thead>
         
      <tr>
        <th class="fon">Citem id </th>
        <th class="fon">category name</th>
        <th class="fon">item name </th>
        <th class="fon">unit </th>
        <th class="fon">quantity</th>
        <th class="fon">item price</th>
        <th class="fon">expire date</th>
        <th class="fon">entered date</th>
        <th class="fon">supplier name</th>
        <th class="fon">record by</th>
      </tr>
     
    </thead>
<?php 
  $rowCount = count($_POST["check"]);
for($i=0;$i<$rowCount;$i++) {
$result = mysqli_query($con, "SELECT * FROM item WHERE item_id='" . $_POST["check"][$i] . "'");
$row[$i]= mysqli_fetch_array($result);
?>
  <tr>
      <th><?php echo $row[$i]['item_id'];?></th>
        <th><?php echo $row[$i]['Catagory_name'];?></th>
        <th><?php echo $row[$i]['Item_name'];?></th>
        <th><?php echo $row[$i]['unit'];?></th>
        <th><?php echo $row[$i]['Quantity'];?></th>
        <th><?php echo $row[$i]['Item_price'];?></th>
        <th><?php echo $row[$i]['Expired_date'];?></th>
        <th><?php echo $row[$i]['Entered_date'];?></th>
        <th><?php echo $row[$i]['supplier_name'];?></th>
        <th><?php echo $row[$i]['Record_by'];?></th>
  </tr>





                </div>
            </div>
        </div>
    </div>
    

</div>
</div>

</div>

<?php
}}
?></table>
<button class="btn btn-primary" onclick="window.print()">first click here to save the above in pdf, then choose saved file to send report</button>
<form action="updateRep.php" method="post" enctype="multipart/form-data">
    <p align="center"><input type="file" name="image" placeholder="choose saved file">
    <input type="hidden" name="id" value="<?php echo $repid; ?>">
     <button type="submit" class="btn btn-success" name="send">Send report</button></p>
</form><?php
?>

</body>
</html>